title: Melvin Harsono # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: >
  <br>
  I'm a professional Software Engineer and AI Consultant with a focus on AI-powered systems, LLMs, and enterprise automation.

  <br><br>
  ğŸ¤– LLM-Powered Chatbots: End-to-end solutions with LangChain, FAISS, Azure OpenAI


  â˜ï¸ Azure Cloud DevOps: Dockerized deployment, CI/CD pipelines, secure API handling


  ğŸ§  ML/DL Expertise: Logistic Regression, Scikit-learn, PyTorch, TensorFlow, model fine-tuning


  ğŸ“Š Dashboards: Dash, Plotly, Streamlit for sales and analytics


  ğŸ›  End-to-End Pipelines: From data ingestion to web UI and cloud deployment
  <br>
  <a href="https://www.linkedin.com/in/melvin-harsono/">
  View My LinkedIn Profile</a>

  
theme: jekyll-theme-minimal
show_downloads: false
footer: false
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
