title: Melvin Harsono # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: >
  <br>
  I'm a professional Software Engineer and AI Consultant specializing in building AI-powered applications, intelligent automation systems, and enterprise-ready web solutions.

  <br><br>
  ğŸ¤– LLM-Powered Systems: Designed and deployed end-to-end RAG-based chatbots using LangChain, FAISS, and Azure OpenAI.
  â˜ï¸ Cloud DevOps: Built and deployed apps to Azure Web Apps using Docker, CI/CD, and secure API handling.
  ğŸ“š Model Development: Experienced in training and fine-tuning ML/DL models using scikit-learn, PyTorch, and TensorFlow.
  ğŸ“Š Interactive Dashboards: Built business dashboards using Dash, Plotly, and Streamlit for sales and data analytics.
  ğŸ›  Full-Stack ML Pipelines: From data ingestion to frontend delivery with clean and scalable code.
  <br>
  <a href="https://www.linkedin.com/in/melvin-harsono/">
  View My LinkedIn Profile</a>

  
theme: jekyll-theme-minimal
show_downloads: false
footer: false
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
